---
version: "3.9"
services:
  master:
    image: ubuntu:20.04
    container_name: master
    hostname: master
    tty: true
    stdin_open: true

  node1:
    image: ubuntu:20.04
    container_name: node1
    hostname: node1
    tty: true
    stdin_open: true

  node2:
    image: ubuntu:20.04
    container_name: node2
    hostname: node2
    tty: true
    stdin_open: true